In [1]:
from utils_1.goenv import GoEnv,_format_state,create_env_copy

import numpy as np

In [2]:
env = GoEnv('black',9)
env.reset()
env.print_board()

. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 


In [3]:
env.step(3)
env.step(20)
env.step(9)
env.step(81)
env.step(80)
env.print_board()

. . . X . . . . . 
X . . . . . . . . 
. . O . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . X 


In [21]:
a = env.get_legal_moves()
actions = env.get_policy_board(a)
print(actions)

print (a)
b = np.array(list(actions[0].flatten()) + [actions[1]])
print (b)

(array([[1, 1, 1, 0, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0]]), 1)
[1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1]
[1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1]


In [15]:
def produce_transformations(matrix, threeD=False):
    if threeD:
        axis = (1,2)
    else:
        axis = (0,1)
        
    matrices = []
    for times in range(4):
        mat = np.rot90(matrix, times, axis)
        flipped_mat = np.flip(mat, 1)
        matrices += [mat, flipped_mat]
    return matrices

mats = produce_transformations(actions[0])
for mat in mats:
    print (mat, end='\n\n')
    

[[1 1 1 0 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0]]

[[1 1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 0 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1]]

[[1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1 1]]

[[0 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 0 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 1]]

[[0 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1 1]
 [1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 0 1 1 1]]

[[1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1]
 [1

In [18]:
A = np.arange(3*2*2).reshape((3,2,2))
print (A, end='\n--------------------------\n\n\n')

mats = produce_transformations(A, threeD=True)
for mat in mats:
    print (mat, end='\n--------------------------\n')

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
--------------------------


[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
--------------------------
[[[ 2  3]
  [ 0  1]]

 [[ 6  7]
  [ 4  5]]

 [[10 11]
  [ 8  9]]]
--------------------------
[[[ 1  3]
  [ 0  2]]

 [[ 5  7]
  [ 4  6]]

 [[ 9 11]
  [ 8 10]]]
--------------------------
[[[ 0  2]
  [ 1  3]]

 [[ 4  6]
  [ 5  7]]

 [[ 8 10]
  [ 9 11]]]
--------------------------
[[[ 3  2]
  [ 1  0]]

 [[ 7  6]
  [ 5  4]]

 [[11 10]
  [ 9  8]]]
--------------------------
[[[ 1  0]
  [ 3  2]]

 [[ 5  4]
  [ 7  6]]

 [[ 9  8]
  [11 10]]]
--------------------------
[[[ 2  0]
  [ 3  1]]

 [[ 6  4]
  [ 7  5]]

 [[10  8]
  [11  9]]]
--------------------------
[[[ 3  1]
  [ 2  0]]

 [[ 7  5]
  [ 6  4]]

 [[11  9]
  [10  8]]]
--------------------------
