In [6]:
from utils_1.goenv import GoEnv,_format_state
import numpy as np
import copy
# from boardFunctions import get_board_moves,npBoard,getWinner,take_step,copy_board,score,isCompleted

In [2]:
board = GoEnv('black',13)

In [3]:
st = board.reset()

In [4]:
print(st.shape)

(17, 13, 13)


In [5]:
print(board.get_legal_moves())
print(board.player_turn())
print(board.give_Board())

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [9]:
a,b,c = board.step(0)
a,b,c = board.step(1)
a,b,c = board.step(5)
a,b,c = board.step(13)
print(board.get_legal_moves())
print(board.player_turn())
print(board.give_Board())

[0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
1
[[ 0 -1  0  0  0  1  0  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [7]:
def createCopyEnv(Env):
    board = GoEnv('black',13)
    board.reset()
    board.history = copy.deepcopy(Env.history)
    board.player_color = copy.deepcopy(Env.player_color)
    board.state = _format_state(board.history,board.player_color, board.board_size)
    board.board = Env.give_Board_Copy()
    board.done = copy.deepcopy(Env.done)
    return board
    

In [8]:
bb = createCopyEnv(board)

In [9]:
a,b,c = bb.step(2)
a,b,c = bb.step(3)
a,b,c = bb.step(4)
a,b,c = bb.step(15)
print(bb.get_legal_moves())
print(bb.player_turn())
print(bb.give_Board())

[0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
1
[[ 0 -1  0 -1  1  1  0  0  0  0  0  0  0]
 [-1  0 -1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [ ]:
bb = board.give_Board_Copy()
curr_p = board.player_turn()
print(curr_p)

In [10]:
print(board.give_Board())

[[ 0 -1  0  0  0  1  0  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [ ]:
get_board_moves(bb,curr_p)

In [ ]:
npBoard(bb)

In [ ]:
bb = take_step(bb,2,curr_p)
print(npBoard(bb))

In [ ]:
curr_p = -1*curr_p
print(curr_p)
bb = take_step(bb,3,curr_p)
curr_p = -1*curr_p
print(curr_p)
bb = take_step(bb,4,curr_p)
curr_p = -1*curr_p
print(curr_p)
bb = take_step(bb,15,curr_p)
print(npBoard(bb))

In [ ]:
print(board.give_Board())

In [ ]:
print(board.curr_score())
print(score(bb))

In [ ]:
print(board.isComplete())
print(isCompleted(bb))

In [ ]:
bb2 = copy_board(bb)
curr_p = -1*curr_p
print(curr_p)
bb2 = take_step(bb2,9,curr_p)

In [ ]:
print(npBoard(bb))
print(npBoard(bb2))

ModuleNotFoundError: No module named 'goenv'

In [12]:
board = GoEnv('black',3)

In [13]:
st = board.reset()

In [14]:
print(board.give_Board())

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [15]:
board.step(0)
print()

In [16]:
board.step(9)
board.step(1)
board.step(9)
board.step(2)
board.step(9)
board.step(3)
board.step(9)
board.step(5)
board.step(9)
board.step(6)
board.step(9)
board.step(7)
board.step(9)
board.step(8)

(array([[[1, 1, 1],
         [1, 0, 1],
         [1, 1, 1]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[1, 1, 1],
         [1, 0, 1],
         [1, 1, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[1, 1, 1],
         [1, 0, 1],
         [1, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[1, 1, 1],
         [1, 0, 1],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[1, 1, 1],
         [1, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[1, 1, 1],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[1, 1, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[1, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0,

In [18]:
print(board.get_legal_moves())

[0 0 0 0 1 0 0 0 0 0]
